### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [ambrosethebuild/paystack_manager#2]
First of all this plugin is a live saver but i want to know how i can put different payment options
thank you
* bank
* transfers

**Comment by ambrosethebuild** [comment]
Hi, the payment options available includes
Bank, card and Mobile money(Ghana).
Depending on the currency supplied the various payment option will be allowed.
GH -> Card & Momo
NG -> Card & Bank

**Comment by GoodnessEzeokafor** [comment]
ok thanks, i noticed when u changed to NGN i got the bank option
